from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

from protocol_utils import ROOT, load_json, validate_payload, write_json, write_text
from generate_machine_response import build_response


if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from mcp import server as mcp_server  # noqa: E402


FIXTURE_PATH = ROOT / "tests" / "fixtures" / "mcp_drive" / "raw_cad_job_request.json"
REPORT_DIR = ROOT / "outputs" / "mcp_drive"
REPORT_JSON_PATH = REPORT_DIR / "latest_agent_run_report.json"
REPORT_MD_PATH = REPORT_DIR / "latest_agent_run_report.md"
VALID_PAYLOAD_JSON_PATH = REPORT_DIR / "generated_build_packet.json"
VALID_PAYLOAD_YAML_PATH = REPORT_DIR / "generated_build_packet.yaml"
INVALID_PAYLOAD_JSON_PATH = REPORT_DIR / "invalid_build_packet.json"
INVALID_PAYLOAD_YAML_PATH = REPORT_DIR / "invalid_build_packet.yaml"
FORBIDDEN_RESPONSE_PATH = REPORT_DIR / "forbidden_action_response.json"
HUMAN_APPROVAL_RESPONSE_PATH = REPORT_DIR / "human_approval_response.json"

DISCOVERY_FILES = [
    "README.md",
    "machine/llms.txt",
    "machine/aether_agent_manifest.json",
    "machine/schema_index.json",
    "machine/tool_catalog.json",
    "machine/permission_manifest.json",
    "machine/error_catalog.json",
    "machine/response_envelope.schema.json",
    "mcp/mcp_manifest.json",
    "openapi/aether.openapi.yaml",
    "mcp/server.py",
]


def run_command(command: list[str]) -> dict[str, Any]:
    result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, check=False)
    return {
        "command": " ".join(command),
        "returncode": result.returncode,
        "status": "PASS" if result.returncode == 0 else "FAIL",
        "stdout": result.stdout.strip(),
        "stderr": result.stderr.strip(),
        "classification": classify_result(result.returncode, result.stderr),
    }


def classify_result(returncode: int, stderr: str) -> str:
    if returncode == 0:
        return "success"
    lower = stderr.lower()
    if "no module named" in lower or "not recognized" in lower:
        return "missing_dependency"
    if "permission" in lower or "access is denied" in lower:
        return "environment_limitation"
    return "code_failure"


def load_fixture() -> dict[str, Any]:
    return load_json(FIXTURE_PATH)


def build_packet_from_raw(raw: dict[str, Any]) -> dict[str, Any]:
    return {
        "protocol_version": "0.2.8",
        "project_id": raw["job_id"],
        "project_name": raw["job_name"],
        "project_type": "fabrication_request",
        "project_description": f"Synthetic local fabrication review request for {raw['part_name']} generated by the MCP drive proof harness.",
        "design_files": [
            {
                "file_name": raw["cad_reference"]["file_name"],
                "file_type": raw["cad_reference"]["file_type"],
                "path": raw["cad_reference"]["path"],
                "notes": raw["cad_reference"]["notes"],
            }
        ],
        "geometry_summary": raw["cad_reference"]["geometry_summary"],
        "bom_items": [
            {
                "item_id": "BKT-001",
                "name": raw["part_name"],
                "category": "fabricated_part",
                "quantity": raw["quantity"],
                "unit": "ea",
                "material": raw["material"]["grade"],
                "dimensions": raw["part_dimensions"],
                "finish": raw["finish_requirement"],
                "supplier_preference": "local_sandbox_only",
                "substitution_allowed": False,
                "notes": f"Requested operations: {', '.join(raw['operations'])}",
            }
        ],
        "material_specs": [
            f"{raw['material']['family']} {raw['material']['grade']} {raw['material']['form']}"
        ],
        "finish_requirements": [raw["finish_requirement"]],
        "dimensions": raw["part_dimensions"],
        "tolerances": [raw["tolerance_notes"]],
        "site_conditions": [
            "Synthetic local submission only.",
            "No physical site visit or external delivery path is authorized.",
        ],
        "location_context": {
            "submission_mode": raw["site_context"]["submission_mode"],
            "physical_site_required": raw["site_context"]["physical_site_required"],
            "delivery_region": raw["site_context"]["delivery_region"],
        },
        "quote_categories": [
            raw["requested_operation"],
            "fabrication_review",
        ],
        "capability_requirements": [
            {
                "capability_id": "laser_cutting",
                "capability_type": "fabrication_process",
                "required_for": "Blank preparation",
                "description": "Cut bracket blank from steel plate using local review assumptions only.",
                "licensed_trade": False,
                "certification_required": False,
                "local_required": True,
                "risk_level": "medium",
                "notes": "Review only; no fabrication approval is granted.",
            },
            {
                "capability_id": "press_brake_forming",
                "capability_type": "fabrication_process",
                "required_for": "Bracket bend operation",
                "description": "Form flange bend to the requested angle within review tolerance.",
                "licensed_trade": False,
                "certification_required": False,
                "local_required": True,
                "risk_level": "medium",
                "notes": "Human review remains required before any external fabrication step.",
            },
        ],
        "install_scope": "Fabrication review only. No install authorization is included.",
        "licensed_trade_required": False,
        "code_review_required": False,
        "permit_review_required": False,
        "safety_notes": [
            "Local-only synthetic fixture; no physical release is authorized.",
            *raw["inspection_notes"],
        ],
        "unknowns": raw["open_questions"],
        "assumptions": [
            "This request stays inside the sandbox-only review boundary.",
            "Human approval is required before any external release or fabrication action.",
        ],
        "human_approval_required": True,
    }


def write_yaml(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def detect_and_repair_invalid_case(valid_payload: dict[str, Any]) -> dict[str, Any]:
    invalid_payload = dict(valid_payload)
    invalid_payload.pop("human_approval_required", None)
    invalid_payload.pop("tolerances", None)
    invalid_errors = validate_payload(invalid_payload, "build_packet.schema.json")

    write_json(INVALID_PAYLOAD_JSON_PATH, invalid_payload)
    write_yaml(INVALID_PAYLOAD_YAML_PATH, invalid_payload)

    repaired_payload = dict(invalid_payload)
    repaired_payload["tolerances"] = valid_payload["tolerances"]
    repaired_payload["human_approval_required"] = True
    repaired_errors = validate_payload(repaired_payload, "build_packet.schema.json")

    write_json(VALID_PAYLOAD_JSON_PATH, repaired_payload)
    write_yaml(VALID_PAYLOAD_YAML_PATH, repaired_payload)

    return {
        "invalid_payload": invalid_payload,
        "invalid_errors": invalid_errors,
        "repaired_payload": repaired_payload,
        "repaired_errors": repaired_errors,
    }


def render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# MCP Drive Agent Proof Report",
        "",
        "## Executive Summary",
        "",
        f"- Proof status: {report['proof_status']}",
        f"- Branch: {report['branch']}",
        f"- Simulated local agent workflow: {report['simulated_agent_workflow']}",
        f"- Regression safety verified inside harness: {report['regression_safety']['attempted'] and report['regression_safety']['passed']}",
        "",
        "## Discovery Evidence",
        "",
    ]
    lines.extend(f"- {item}" for item in report["discovery"]["found_files"])
    lines.extend([
        "",
        "## Schema and Contract Surfaces",
        "",
    ])
    lines.extend(f"- {item}" for item in report["schema_contracts"])
    lines.extend([
        "",
        "## Payload Validation",
        "",
        f"- Raw fixture: {report['raw_fixture_path']}",
        f"- Generated payload: {report['generated_payload_path']}",
        f"- Invalid case detected: {report['validation']['invalid_case_detected']}",
        f"- Repair successful: {report['validation']['repair_successful']}",
        "",
        "## Forbidden Action Discipline",
        "",
        f"- Forbidden action attempted: {report['forbidden_action_discipline']['attempted_action']}",
        f"- Action blocked locally: {report['forbidden_action_discipline']['blocked']}",
        f"- External action taken: {report['forbidden_action_discipline']['external_action_taken']}",
        "",
        "## Human Approval Preservation",
        "",
        f"- human_approval_required on payload: {report['human_approval_preservation']['payload_requires_human_approval']}",
        f"- Human approval response status: {report['human_approval_preservation']['response_status']}",
        f"- Automatic execution prevented: {report['human_approval_preservation']['automatic_execution_prevented']}",
        "",
        "## Commands Run",
        "",
    ])
    lines.extend(f"- {item['command']}: {item['status']} ({item['classification']})" for item in report["commands_run"])
    lines.extend([
        "",
        "## Artifacts Generated",
        "",
    ])
    lines.extend(f"- {item}" for item in report["artifacts_generated"])
    lines.extend([
        "",
        "## Guardrail Boundaries",
        "",
    ])
    if report["guardrail_boundaries_encountered"]:
        lines.extend(f"- {item}" for item in report["guardrail_boundaries_encountered"])
    else:
        lines.append("- None")
    lines.extend([
        "",
        "## What This Proves",
        "",
        "- Discovery surfaces were found locally through repo files.",
        "- A synthetic CAD/job-style request was mapped into a machine-readable Build Packet.",
        "- Local schema validation caught an invalid case and the harness repaired it without hiding the failure.",
        "- Forbidden external actions were blocked and human approval gates remained preserved.",
        "",
        "## What This Does Not Prove",
        "",
        "- This is a bounded local proof loop only.",
        "- This does not prove a live external LLM or real MCP service integration.",
        "- This does not deploy a gateway, send email, call webhooks, or contact suppliers.",
    ])
    if report["proof_status"] != "PASS":
        lines.extend(["", "## Missing Evidence", ""])
        lines.extend(f"- {item}" for item in report["missing_evidence"])
    return "\n".join(lines) + "\n"


def determine_status(criteria: dict[str, bool], missing_evidence: list[str]) -> str:
    if all(criteria.values()):
        return "PASS"
    if criteria["discovery"] and criteria["schema_compliance"] and criteria["local_validation"] and criteria["forbidden_action_discipline"] and criteria["human_approval_preservation"] and criteria["artifact_generation"] and not criteria["regression_safety"]:
        if not missing_evidence:
            missing_evidence.append("Regression safety was not proven inside the proof harness run.")
        return "INSUFFICIENT_EVIDENCE"
    return "FAIL"


def current_branch() -> str:
    result = subprocess.run(["git", "branch", "--show-current"], cwd=ROOT, capture_output=True, text=True, check=False)
    if result.returncode == 0 and result.stdout.strip():
        return result.stdout.strip()
    return "unknown"


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the bounded local MCP drive agent proof.")
    parser.add_argument("--skip-regression-check", action="store_true")
    args = parser.parse_args()

    raw_fixture = load_fixture()
    found_files = [item for item in DISCOVERY_FILES if (ROOT / item).exists()]
    missing_files = [item for item in DISCOVERY_FILES if not (ROOT / item).exists()]

    agent_manifest = mcp_server.read_aether_agent_manifest()
    schema_index = mcp_server.read_schema_index()
    tool_catalog = mcp_server.read_tool_catalog()
    permission_manifest = mcp_server.read_permission_manifest()
    mcp_manifest = load_json(ROOT / "mcp" / "mcp_manifest.json")

    generated_payload = build_packet_from_raw(raw_fixture)
    build_packet_errors = validate_payload(generated_payload, "build_packet.schema.json")

    invalid_case = detect_and_repair_invalid_case(generated_payload)

    forbidden_action_result = mcp_server.refuse_forbidden_action("send_email")
    forbidden_response = build_response("MCP_TOOL_REFUSAL", "send_email", raw_fixture["job_id"])
    write_json(FORBIDDEN_RESPONSE_PATH, forbidden_response)

    human_approval_response = build_response("HUMAN_APPROVAL_REQUIRED", "external_release", raw_fixture["job_id"])
    write_json(HUMAN_APPROVAL_RESPONSE_PATH, human_approval_response)

    commands_run = [
        {
            "command": "local_schema_validation generated_build_packet",
            "returncode": 0 if not build_packet_errors else 1,
            "status": "PASS" if not build_packet_errors else "FAIL",
            "stdout": "Local schema validation completed.",
            "stderr": "\n".join(build_packet_errors),
            "classification": "success" if not build_packet_errors else "code_failure",
        },
        {
            "command": "local_schema_validation invalid_build_packet",
            "returncode": 1 if invalid_case["invalid_errors"] else 0,
            "status": "PASS" if invalid_case["invalid_errors"] else "FAIL",
            "stdout": "Invalid payload check completed.",
            "stderr": "\n".join(invalid_case["invalid_errors"]),
            "classification": "expected_guardrail_block" if invalid_case["invalid_errors"] else "code_failure",
        },
        {
            "command": "mcp.refuse_forbidden_action send_email",
            "returncode": 0 if forbidden_action_result.get("status") in {"PASS", "BLOCKED"} else 1,
            "status": "PASS" if forbidden_action_result.get("status") in {"PASS", "BLOCKED"} else "FAIL",
            "stdout": json.dumps(forbidden_action_result),
            "stderr": "",
            "classification": "expected_guardrail_block",
        },
    ]

    regression_result: dict[str, Any] = {
        "attempted": False,
        "passed": False,
        "command": "python -m pytest -q",
        "classification": "not_run",
        "stdout": "",
        "stderr": "",
    }
    if not args.skip_regression_check:
        regression_command = run_command([sys.executable, "-m", "pytest", "-q"])
        regression_result = {
            "attempted": True,
            "passed": regression_command["returncode"] == 0,
            "command": regression_command["command"],
            "classification": regression_command["classification"],
            "stdout": regression_command["stdout"],
            "stderr": regression_command["stderr"],
        }
        commands_run.append(regression_command)

    criteria = {
        "discovery": len(found_files) == len(DISCOVERY_FILES) and "generate_machine_response" in {tool["tool_id"] for tool in tool_catalog["tools"]} and "generate_machine_response" in mcp_manifest["tools"],
        "schema_compliance": not build_packet_errors and len(schema_index["schemas"]) >= 1,
        "local_validation": bool(invalid_case["invalid_errors"]) and not invalid_case["repaired_errors"],
        "forbidden_action_discipline": forbidden_response["status"] == "BLOCKED" and forbidden_response["external_action_taken"] is False,
        "human_approval_preservation": generated_payload["human_approval_required"] is True and human_approval_response["status"] == "BLOCKED" and human_approval_response["human_review_required"] is True,
        "artifact_generation": True,
        "regression_safety": regression_result["passed"],
    }

    expected_artifact_paths = [
        VALID_PAYLOAD_JSON_PATH,
        VALID_PAYLOAD_YAML_PATH,
        INVALID_PAYLOAD_JSON_PATH,
        INVALID_PAYLOAD_YAML_PATH,
        FORBIDDEN_RESPONSE_PATH,
        HUMAN_APPROVAL_RESPONSE_PATH,
        REPORT_JSON_PATH,
        REPORT_MD_PATH,
    ]
    pre_report_artifact_paths = [
        VALID_PAYLOAD_JSON_PATH,
        VALID_PAYLOAD_YAML_PATH,
        INVALID_PAYLOAD_JSON_PATH,
        INVALID_PAYLOAD_YAML_PATH,
        FORBIDDEN_RESPONSE_PATH,
        HUMAN_APPROVAL_RESPONSE_PATH,
    ]
    criteria["artifact_generation"] = all(path.exists() for path in pre_report_artifact_paths)

    artifacts_generated = [
        str(path.relative_to(ROOT)).replace("\\", "/")
        for path in pre_report_artifact_paths
        if path.exists()
    ]

    missing_evidence = list(missing_files)
    if build_packet_errors:
        missing_evidence.append("Generated payload did not validate against build_packet.schema.json.")
    if not invalid_case["invalid_errors"]:
        missing_evidence.append("The harness did not detect an invalid payload case.")
    if invalid_case["repaired_errors"]:
        missing_evidence.append("The repaired payload still failed local schema validation.")
    if forbidden_response["status"] != "BLOCKED":
        missing_evidence.append("Forbidden action refusal did not produce a blocked response.")
    if not criteria["artifact_generation"]:
        missing_evidence.append("One or more expected proof artifacts were not generated.")
    if not regression_result["passed"] and regression_result["attempted"]:
        missing_evidence.append("Regression safety failed during python -m pytest -q.")

    guardrail_boundaries = []
    if forbidden_action_result.get("external_action_taken") is False:
        guardrail_boundaries.append("send_email remained blocked locally with no external action.")
    if generated_payload["human_approval_required"] is True:
        guardrail_boundaries.append("human_approval_required remained true on the generated payload.")
    if human_approval_response["status"] == "BLOCKED":
        guardrail_boundaries.append("external_release remained blocked pending human approval.")

    report = {
        "proof_status": determine_status(criteria, missing_evidence),
        "branch": current_branch(),
        "simulated_agent_workflow": True,
        "raw_fixture_path": str(FIXTURE_PATH.relative_to(ROOT)).replace("\\", "/"),
        "generated_payload_path": str(VALID_PAYLOAD_JSON_PATH.relative_to(ROOT)).replace("\\", "/"),
        "discovery": {
            "found_files": found_files,
            "missing_files": missing_files,
            "starting_points": ["README.md", "machine/llms.txt"],
            "mcp_server_surface_importable": True,
        },
        "schema_contracts": [
            "protocols/build_intent/schemas/build_packet.schema.json",
            "machine/response_envelope.schema.json",
            "mcp/mcp_manifest.json",
            "openapi/aether.openapi.yaml",
        ],
        "validation": {
            "generated_payload_errors": build_packet_errors,
            "invalid_case_detected": bool(invalid_case["invalid_errors"]),
            "invalid_case_errors": invalid_case["invalid_errors"],
            "repair_successful": not invalid_case["repaired_errors"],
            "repaired_payload_errors": invalid_case["repaired_errors"],
            "validator_scope": "local schema validation only",
        },
        "forbidden_action_discipline": {
            "attempted_action": "send_email",
            "blocked": forbidden_response["status"] == "BLOCKED",
            "external_action_taken": forbidden_response["external_action_taken"],
            "refusal_message": forbidden_response["message"],
        },
        "human_approval_preservation": {
            "payload_requires_human_approval": generated_payload["human_approval_required"],
            "response_status": human_approval_response["status"],
            "automatic_execution_prevented": human_approval_response["status"] == "BLOCKED",
            "approval_required_for": human_approval_response.get("approval_required_for", []),
        },
        "commands_run": commands_run,
        "artifacts_generated": artifacts_generated,
        "regression_safety": regression_result,
        "guardrail_boundaries_encountered": guardrail_boundaries,
        "missing_evidence": missing_evidence,
        "tool_discovery": [tool["tool_id"] for tool in tool_catalog["tools"]],
        "forbidden_actions_known": permission_manifest["global_forbidden_actions"],
    }

    write_json(REPORT_JSON_PATH, report)
    write_text(REPORT_MD_PATH, render_markdown(report))

    report["artifacts_generated"] = [
        str(path.relative_to(ROOT)).replace("\\", "/")
        for path in expected_artifact_paths
        if path.exists()
    ]
    write_json(REPORT_JSON_PATH, report)
    write_text(REPORT_MD_PATH, render_markdown(report))

    print(f"Proof status: {report['proof_status']}")
    print(f"Wrote: {REPORT_JSON_PATH}")
    print(f"Wrote: {REPORT_MD_PATH}")
    return 0 if report["proof_status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())